var PL_IMAGES={paddy_ap:"ap_launch_opp.png",maize_mh:"mh_launch_opp.png"};
var PL_MATRIX_IMAGES={paddy_ap:"ap_launch_matrix.png",maize_mh:"mh_launch_matrix.png"};
var PL_DATA={paddy_ap:{
scenario:{crop:"Paddy",product:"InficusPre-Mix 360 SC",targetWeeds:["Barnyard Grass","Variable Flatsedge","Globe Fimbry"],geography:"Andhra Pradesh"},
districts:[
{name:"East Godavari",unmetOpp:92,compIntensity:75,marketPot:18.5,productFit:"Strong",topWeeds:["Barnyard Grass","Variable Flatsedge","Pickerelweed"],competitors:["Nominee Gold (UPL)","Clincher (Dow)","Almix (DuPont)"],estPotCr:4.2,compShare:{UPL:35,Syngenta:20,DuPont:15,Generic:30},molecules:{Pretilachlor:40,Bispyribac:25,Pyrazosulfuron:20,"2,4-D":15},gaps:["Pre-mix (Pretilachlor+Bispyribac)","Sedge+Broadleaf combo"],wave:1,waveReason:"Highest unmet opp + strong product fit; UPL dominance showing weed escape signals"},
{name:"West Godavari",unmetOpp:88,compIntensity:70,marketPot:16.2,productFit:"Strong",topWeeds:["Barnyard Grass","Pickerelweed","Variable Flatsedge"],competitors:["Nominee Gold (UPL)","Clincher (Dow)"],estPotCr:3.8,compShare:{UPL:38,Dow:18,Generic:44},molecules:{Pretilachlor:35,Cyhalofop:22,Bispyribac:28,"2,4-D":15},gaps:["3-way pre-mix","Post-emergent combo"],wave:1,waveReason:"High farmer dissatisfaction with UPL; strong conversion opportunity"},
{name:"Guntur",unmetOpp:82,compIntensity:45,marketPot:14.8,productFit:"Strong",topWeeds:["Globe Fimbry","Variable Flatsedge","Barnyard Grass"],competitors:["Almix (DuPont)","Sunrice (Dhanuka)"],estPotCr:3.5,compShare:{DuPont:30,Dhanuka:15,Generic:55},molecules:{Pyrazosulfuron:45,Pretilachlor:25,Bensulfuron:18,"2,4-D":12},gaps:["Sedge-specific pre-mix","Broad-spectrum single shot"],wave:1,waveReason:"Low competition; high sedge pressure creates clear product positioning"},
{name:"Srikakulam",unmetOpp:78,compIntensity:40,marketPot:10.5,productFit:"Strong",topWeeds:["Barnyard Grass","Variable Flatsedge"],competitors:["Nominee Gold (UPL)","Generic"],estPotCr:2.4,compShare:{UPL:25,Generic:65,Others:10},molecules:{Pretilachlor:50,Bispyribac:20,"2,4-D":18,Butachlor:12},gaps:["Modern pre-mix replacement for Butachlor","Resistance-breaking combo"],wave:1,waveReason:"Generic-dominated; easy displacement with efficacy demos"},
{name:"Krishna",unmetOpp:75,compIntensity:48,marketPot:13.2,productFit:"Strong",topWeeds:["Variable Flatsedge","Globe Fimbry","Barnyard Grass"],competitors:["Almix (DuPont)","Generic"],estPotCr:3.1,compShare:{DuPont:28,Generic:52,Others:20},molecules:{Pyrazosulfuron:38,Pretilachlor:30,Bensulfuron:18,"2,4-D":14},gaps:["Pre-mix for sedge+grass complex","Tank-mix replacement"],wave:1,waveReason:"Strong sedge problem; DuPont losing share to generics"},
{name:"Visakhapatnam",unmetOpp:65,compIntensity:62,marketPot:12.8,productFit:"Moderate",topWeeds:["Barnyard Grass","Knotgrass"],competitors:["Nominee Gold (UPL)","Ricestar (Bayer)"],estPotCr:2.8,compShare:{UPL:32,Bayer:22,Syngenta:15,Generic:31},molecules:{Pretilachlor:35,Bispyribac:28,Cyhalofop:22,"2,4-D":15},gaps:["Knotgrass-specific solution","Resistance management pre-mix"],wave:2,waveReason:"Moderate opportunity; needs differentiation vs Bayer"},
{name:"Vizianagaram",unmetOpp:58,compIntensity:42,marketPot:7.5,productFit:"Moderate",topWeeds:["Variable Flatsedge","Pickerelweed"],competitors:["DuPont (Moderate)","Generic"],estPotCr:1.8,compShare:{DuPont:22,Generic:60,Others:18},molecules:{Pyrazosulfuron:40,Pretilachlor:28,"2,4-D":20,Others:12},gaps:["Broadleaf+Sedge combo","FPO-channel specific packs"],wave:2,waveReason:"Generic heavy market; moderate potential with targeted approach"},
{name:"Kurnool",unmetOpp:55,compIntensity:35,marketPot:9.2,productFit:"Moderate",topWeeds:["Variable Flatsedge","Knotgrass"],competitors:["Generic","DuPont (Low)"],estPotCr:2.1,compShare:{DuPont:12,Generic:72,Others:16},molecules:{Pretilachlor:45,Pyrazosulfuron:25,"2,4-D":18,Others:12},gaps:["Affordable pre-mix for smallholders","Sedge management solution"],wave:2,waveReason:"Price-sensitive; needs competitive pricing strategy"},
{name:"Prakasam",unmetOpp:52,compIntensity:38,marketPot:8.8,productFit:"Moderate",topWeeds:["Water Primrose","Pickerelweed"],competitors:["Dhanuka (Moderate)","Generic"],estPotCr:2.0,compShare:{Dhanuka:20,Generic:62,Others:18},molecules:{Pretilachlor:35,"2,4-D":30,Metsulfuron:18,Others:17},gaps:["Broadleaf-specific pre-mix","Water Primrose targeted"],wave:2,waveReason:"Broadleaf-dominant; product positioning requires adaptation"},
{name:"Nellore",unmetOpp:42,compIntensity:32,marketPot:7.2,productFit:"Moderate",topWeeds:["Pickerelweed","Knotgrass"],competitors:["Dhanuka (Low)","Generic"],estPotCr:1.6,compShare:{Dhanuka:15,Generic:70,Others:15},molecules:{Pretilachlor:40,"2,4-D":28,Oxadiazon:18,Others:14},gaps:["Pre-emergent+Post-emergent kit","Pickerelweed targeted"],wave:2,waveReason:"Moderate potential; generic displacement opportunity"},
{name:"YSR Kadapa",unmetOpp:35,compIntensity:55,marketPot:5.5,productFit:"Weak",topWeeds:["Globe Fimbry","Water Primrose"],competitors:["DuPont (Strong)","Bayer (Moderate)"],estPotCr:1.2,compShare:{DuPont:35,Bayer:25,Generic:40},molecules:{Pyrazosulfuron:40,Bensulfuron:25,"2,4-D":20,Others:15},gaps:["Limited gap; incumbents strong"],wave:3,waveReason:"Strong incumbents; expansion only after Wave 1-2 success"},
{name:"Chittoor",unmetOpp:25,compIntensity:72,marketPot:4.8,productFit:"Weak",topWeeds:["Knotgrass","Water Primrose"],competitors:["Bayer (Strong)","UPL (Strong)"],estPotCr:0.9,compShare:{Bayer:35,UPL:30,Syngenta:15,Generic:20},molecules:{Cyhalofop:30,Pretilachlor:25,Oxadiazon:25,"2,4-D":20},gaps:["Saturated; no clear gap"],wave:3,waveReason:"High competition; low weed pressure; monitor only"},
{name:"Anantapur",unmetOpp:20,compIntensity:68,marketPot:3.2,productFit:"Weak",topWeeds:["Knotgrass","Water Primrose"],competitors:["Bayer (Strong)","Syngenta (Moderate)"],estPotCr:0.6,compShare:{Bayer:32,Syngenta:28,Generic:40},molecules:{Pretilachlor:30,Oxadiazon:28,"2,4-D":22,Others:20},gaps:["Minimal; paddy not primary"],wave:3,waveReason:"Paddy negligible; not strategic for launch"}
],
stageGates:{regulatory:"High",supply:"High",distributor:"Medium"},
impact:{totalPotCr:23.8,wave1Cr:17.0,wave2Cr:10.3,wave3Cr:2.7,districtsTargeted:13,wave1Count:5,wave2Count:5,wave3Count:3}
},
maize_mh:{
scenario:{crop:"Maize",product:"InficusMaize Pro 450 SC",targetWeeds:["Purple Nutsedge","Congress Grass","Bermuda Grass"],geography:"Maharashtra"},
districts:[
{name:"Aurangabad",unmetOpp:90,compIntensity:65,marketPot:17.5,productFit:"Strong",topWeeds:["Purple Nutsedge","Congress Grass","Bermuda Grass"],competitors:["Sempra (Bayer)","Atrazine (Syngenta)"],estPotCr:4.0,compShare:{Bayer:30,Syngenta:25,Generic:45},molecules:{Atrazine:35,Halosulfuron:25,Tembotrione:20,"2,4-D":20},gaps:["Nutsedge+Broadleaf pre-mix","Topramezone combo"],wave:1,waveReason:"Highest nutsedge pressure; Bayer losing satisfaction scores"},
{name:"Kolhapur",unmetOpp:85,compIntensity:35,marketPot:12.8,productFit:"Strong",topWeeds:["Congress Grass","Bermuda Grass"],competitors:["Syngenta (Low)","Bayer (Low)"],estPotCr:3.2,compShare:{Syngenta:18,Bayer:12,Generic:70},molecules:{Atrazine:50,"2,4-D":25,Tembotrione:15,Others:10},gaps:["Post-emergent grass+broadleaf combo","Modern Atrazine replacement"],wave:1,waveReason:"Minimal competition; generic-dominated with high weed pressure"},
{name:"Ahmednagar",unmetOpp:80,compIntensity:48,marketPot:14.2,productFit:"Strong",topWeeds:["Congress Grass","Bermuda Grass","Purple Nutsedge"],competitors:["Syngenta (Moderate)","Generic"],estPotCr:3.5,compShare:{Syngenta:28,Generic:55,Others:17},molecules:{Atrazine:42,Tembotrione:22,"2,4-D":20,Halosulfuron:16},gaps:["Broad-spectrum single-shot","Resistance-breaking combo"],wave:1,waveReason:"High Congress Grass; Syngenta Atrazine showing resistance signals"},
{name:"Pune",unmetOpp:76,compIntensity:68,marketPot:15.5,productFit:"Strong",topWeeds:["Purple Nutsedge","Bermuda Grass"],competitors:["Sempra (Bayer)","Roundup (Bayer)"],estPotCr:3.6,compShare:{Bayer:38,Syngenta:20,Generic:42},molecules:{Halosulfuron:30,Atrazine:28,Tembotrione:22,"2,4-D":20},gaps:["Non-Bayer nutsedge solution","Pre-mix for mixed weed flora"],wave:1,waveReason:"Large market; Bayer monopoly creates displacement opportunity"},
{name:"Nashik",unmetOpp:72,compIntensity:52,marketPot:13.2,productFit:"Strong",topWeeds:["Bermuda Grass","Purple Nutsedge"],competitors:["Bayer (Moderate)","Generic"],estPotCr:3.0,compShare:{Bayer:28,Generic:55,Others:17},molecules:{Atrazine:38,Tembotrione:25,Halosulfuron:20,"2,4-D":17},gaps:["Grass-specific modern solution","Roundup replacement"],wave:1,waveReason:"Bermuda Grass dominant; farmers seeking non-Roundup alternatives"},
{name:"Latur",unmetOpp:62,compIntensity:55,marketPot:9.8,productFit:"Moderate",topWeeds:["Congress Grass","Pigweed"],competitors:["Syngenta (Strong)","Bayer (Moderate)"],estPotCr:2.2,compShare:{Syngenta:32,Bayer:22,Generic:46},molecules:{Atrazine:40,"2,4-D":28,Topramezone:18,Others:14},gaps:["Broadleaf complex pre-mix","Pigweed targeted"],wave:2,waveReason:"Moderate opportunity; needs differentiation from Syngenta Atrazine"},
{name:"Jalgaon",unmetOpp:58,compIntensity:30,marketPot:8.2,productFit:"Moderate",topWeeds:["Pigweed","Purple Nutsedge"],competitors:["Generic","Bayer (Low)"],estPotCr:1.9,compShare:{Bayer:12,Generic:75,Others:13},molecules:{Atrazine:48,"2,4-D":25,Others:27},gaps:["Modern broadleaf control","Pigweed pre-mix"],wave:2,waveReason:"Generic-heavy; easy entry with efficacy positioning"},
{name:"Buldhana",unmetOpp:55,compIntensity:28,marketPot:6.5,productFit:"Moderate",topWeeds:["Purple Nutsedge","Congress Grass"],competitors:["Generic","Syngenta (Low)"],estPotCr:1.5,compShare:{Syngenta:15,Generic:72,Others:13},molecules:{Atrazine:52,"2,4-D":22,Halosulfuron:15,Others:11},gaps:["Affordable nutsedge solution","Smallholder packs"],wave:2,waveReason:"Low competition; needs distribution build-up"},
{name:"Satara",unmetOpp:52,compIntensity:45,marketPot:7.5,productFit:"Moderate",topWeeds:["Bermuda Grass","Goosegrass"],competitors:["Syngenta (Moderate)","Nissan (Low)"],estPotCr:1.7,compShare:{Syngenta:25,Nissan:10,Generic:65},molecules:{Atrazine:40,Tembotrione:25,"2,4-D":18,Others:17},gaps:["Grass-specific modern herbicide","Tank-mix replacement"],wave:2,waveReason:"Grass-dominant; requires grass-specific positioning"},
{name:"Sangli",unmetOpp:42,compIntensity:48,marketPot:6.8,productFit:"Moderate",topWeeds:["Purple Nutsedge","Bermuda Grass"],competitors:["Bayer (Moderate)","Generic"],estPotCr:1.5,compShare:{Bayer:25,Generic:55,Others:20},molecules:{Halosulfuron:28,Atrazine:35,"2,4-D":22,Others:15},gaps:["Limited differentiation possible"],wave:2,waveReason:"Moderate potential; co-marketing with dealer network"},
{name:"Solapur",unmetOpp:28,compIntensity:65,marketPot:4.2,productFit:"Weak",topWeeds:["Common Purslane","Goosegrass"],competitors:["Syngenta (Strong)","Bayer (Strong)"],estPotCr:0.8,compShare:{Syngenta:30,Bayer:28,Generic:42},molecules:{Atrazine:40,"2,4-D":28,Others:32},gaps:["Saturated market"],wave:3,waveReason:"Low maize area; strong incumbents"},
{name:"Nanded",unmetOpp:38,compIntensity:58,marketPot:5.5,productFit:"Weak",topWeeds:["Pigweed","Goosegrass"],competitors:["Bayer (Strong)","UPL (Moderate)"],estPotCr:1.0,compShare:{Bayer:30,UPL:20,Generic:50},molecules:{Atrazine:42,"2,4-D":25,Tembotrione:18,Others:15},gaps:["Limited; soybean-dominant"],wave:3,waveReason:"Soybean primary; maize secondary crop"},
{name:"Amravati",unmetOpp:22,compIntensity:62,marketPot:3.8,productFit:"Weak",topWeeds:["Goosegrass","Common Purslane"],competitors:["UPL (Strong)","Syngenta (Moderate)"],estPotCr:0.7,compShare:{UPL:28,Syngenta:22,Generic:50},molecules:{Atrazine:38,"2,4-D":30,Others:32},gaps:["None significant"],wave:3,waveReason:"Cotton belt; maize minor"},
{name:"Nagpur",unmetOpp:18,compIntensity:72,marketPot:3.2,productFit:"Weak",topWeeds:["Goosegrass","Common Purslane"],competitors:["UPL (Strong)","Bayer (Strong)"],estPotCr:0.5,compShare:{UPL:32,Bayer:28,Generic:40},molecules:{Atrazine:35,"2,4-D":28,Others:37},gaps:["None"],wave:3,waveReason:"No strategic value for maize"},
{name:"Beed",unmetOpp:15,compIntensity:60,marketPot:2.5,productFit:"Weak",topWeeds:["Common Purslane","Pigweed"],competitors:["Syngenta (Strong)","Generic"],estPotCr:0.4,compShare:{Syngenta:30,Generic:55,Others:15},molecules:{Atrazine:45,"2,4-D":30,Others:25},gaps:["None"],wave:3,waveReason:"Drought-prone; minimal maize"}
],
stageGates:{regulatory:"High",supply:"Medium",distributor:"Medium"},
impact:{totalPotCr:19.7,wave1Cr:17.3,wave2Cr:9.8,wave3Cr:3.4,districtsTargeted:15,wave1Count:5,wave2Count:5,wave3Count:5}
}};
