var PL_IMAGES={paddy_ap:"ap_launch_opp.png",maize_mh:"mh_launch_opp.png"};
var PL_MATRIX_IMAGES={paddy_ap:"ap_launch_matrix.png",maize_mh:"mh_launch_matrix.png"};

/* ═══ WEED TYPES PER CROP-STATE ═══ */
var PL_WEED_TYPES={
paddy_ap:[
{id:"PW1",name:"Barnyard Grass",sci:"Echinochloa crus-galli",type:"Grass",severity:"High",prevalence:87,
 control:"Pretilachlor, Bispyribac-Na",resistRisk:"Low",peakStage:"Transplanting",controlWindow:"0–15 DAT",
 lossRange:"40–80%",threshold:"5–10 plants/m²",
 distData:{
  "East Godavari":{prev:82,opp:92,fit:"Strong",comp:["Nominee Gold (UPL)","Clincher (Dow)"],gap:"Pre-mix resistance breaker"},
  "West Godavari":{prev:78,opp:88,fit:"Strong",comp:["Nominee Gold (UPL)","Clincher (Dow)"],gap:"Post-emergent combo"},
  "Guntur":{prev:55,opp:72,fit:"Strong",comp:["Almix (DuPont)"],gap:"Broad-spectrum single shot"},
  "Srikakulam":{prev:72,opp:78,fit:"Strong",comp:["Nominee Gold (UPL)","Generic"],gap:"Modern replacement for Butachlor"},
  "Krishna":{prev:48,opp:65,fit:"Moderate",comp:["DuPont","Generic"],gap:"Pre-mix for grass+sedge complex"},
  "Visakhapatnam":{prev:68,opp:70,fit:"Strong",comp:["Nominee Gold (UPL)","Ricestar (Bayer)"],gap:"Knotgrass+Barnyard combo"},
  "Vizianagaram":{prev:45,opp:52,fit:"Moderate",comp:["DuPont","Generic"],gap:"FPO-channel specific packs"},
  "Kurnool":{prev:42,opp:48,fit:"Moderate",comp:["Generic","DuPont (Low)"],gap:"Affordable pre-mix"},
  "Prakasam":{prev:35,opp:38,fit:"Weak",comp:["Dhanuka","Generic"],gap:"Not primary weed"},
  "Nellore":{prev:40,opp:42,fit:"Moderate",comp:["Dhanuka","Generic"],gap:"Secondary priority"},
  "YSR Kadapa":{prev:30,opp:28,fit:"Weak",comp:["DuPont (Strong)","Bayer"],gap:"Limited"},
  "Chittoor":{prev:22,opp:20,fit:"Weak",comp:["Bayer (Strong)","UPL"],gap:"Saturated"},
  "Anantapur":{prev:18,opp:15,fit:"Weak",comp:["Bayer","Syngenta"],gap:"Minimal"}
 }},
{id:"PW2",name:"Variable Flatsedge",sci:"Cyperus difformis",type:"Sedge",severity:"High",prevalence:74,
 control:"Pyrazosulfuron, Bensulfuron",resistRisk:"Medium",peakStage:"Tillering",controlWindow:"7–21 DAT",
 lossRange:"25–50%",threshold:"15–20 plants/m²",
 distData:{
  "East Godavari":{prev:60,opp:75,fit:"Strong",comp:["Almix (DuPont)","Londax (DuPont)"],gap:"Sedge+Broadleaf combo"},
  "West Godavari":{prev:58,opp:72,fit:"Strong",comp:["UPL","DuPont"],gap:"3-way pre-mix"},
  "Guntur":{prev:48,opp:80,fit:"Strong",comp:["Almix (DuPont)","Sunrice (Dhanuka)"],gap:"Sedge-specific pre-mix"},
  "Srikakulam":{prev:55,opp:68,fit:"Strong",comp:["UPL","Generic"],gap:"Resistance-breaking combo"},
  "Krishna":{prev:72,opp:82,fit:"Strong",comp:["DuPont","Generic"],gap:"Tank-mix replacement"},
  "Visakhapatnam":{prev:50,opp:55,fit:"Moderate",comp:["UPL","Bayer"],gap:"Differentiation needed"},
  "Vizianagaram":{prev:65,opp:62,fit:"Moderate",comp:["DuPont","Generic"],gap:"Broadleaf+Sedge combo"},
  "Kurnool":{prev:62,opp:60,fit:"Moderate",comp:["Generic","DuPont (Low)"],gap:"Sedge management solution"},
  "Prakasam":{prev:40,opp:42,fit:"Moderate",comp:["Dhanuka","Generic"],gap:"Secondary target"},
  "Nellore":{prev:35,opp:35,fit:"Weak",comp:["Generic"],gap:"Low priority"},
  "YSR Kadapa":{prev:38,opp:32,fit:"Weak",comp:["DuPont (Strong)"],gap:"Limited"},
  "Chittoor":{prev:25,opp:18,fit:"Weak",comp:["Bayer","UPL"],gap:"Saturated"},
  "Anantapur":{prev:20,opp:12,fit:"Weak",comp:["Bayer","Syngenta"],gap:"None"}
 }},
{id:"PW3",name:"Pickerelweed",sci:"Monochoria vaginalis",type:"Broadleaf",severity:"Medium",prevalence:61,
 control:"2,4-D, Metsulfuron",resistRisk:"Low",peakStage:"Tillering",controlWindow:"15–30 DAT",
 lossRange:"20–35%",threshold:"10 plants/m²",
 distData:{
  "East Godavari":{prev:55,opp:68,fit:"Strong",comp:["Weedmar (Dhanuka)","2,4-D (Generic)"],gap:"Broadleaf pre-mix"},
  "West Godavari":{prev:50,opp:65,fit:"Strong",comp:["UPL","2,4-D (Generic)"],gap:"Modern broadleaf control"},
  "Guntur":{prev:40,opp:55,fit:"Moderate",comp:["DuPont","Dhanuka"],gap:"Combo product"},
  "Srikakulam":{prev:45,opp:60,fit:"Strong",comp:["Generic"],gap:"Replace 2,4-D generics"},
  "Krishna":{prev:35,opp:48,fit:"Moderate",comp:["DuPont","Generic"],gap:"Mixed weed flora"},
  "Visakhapatnam":{prev:42,opp:50,fit:"Moderate",comp:["UPL","Bayer"],gap:"Differentiated broadleaf"},
  "Vizianagaram":{prev:38,opp:52,fit:"Moderate",comp:["DuPont","Generic"],gap:"FPO channel entry"},
  "Kurnool":{prev:25,opp:30,fit:"Weak",comp:["Generic"],gap:"Price-driven market"},
  "Prakasam":{prev:48,opp:58,fit:"Moderate",comp:["Dhanuka","Generic"],gap:"Broadleaf-specific pre-mix"},
  "Nellore":{prev:62,opp:65,fit:"Strong",comp:["Dhanuka (Low)","Generic"],gap:"Pickerelweed targeted"},
  "YSR Kadapa":{prev:28,opp:22,fit:"Weak",comp:["DuPont","Bayer"],gap:"Limited"},
  "Chittoor":{prev:30,opp:18,fit:"Weak",comp:["Bayer","UPL"],gap:"No gap"},
  "Anantapur":{prev:15,opp:10,fit:"Weak",comp:["Bayer","Syngenta"],gap:"None"}
 }},
{id:"PW4",name:"Globe Fimbry",sci:"Fimbristylis miliacea",type:"Sedge",severity:"Medium",prevalence:58,
 control:"Pyrazosulfuron",resistRisk:"Low",peakStage:"Tillering",controlWindow:"10–25 DAT",
 lossRange:"15–25%",threshold:"20–30 plants/m²",
 distData:{
  "East Godavari":{prev:50,opp:62,fit:"Strong",comp:["Almix (DuPont)","Sunrice (Dhanuka)"],gap:"Sedge combo"},
  "West Godavari":{prev:45,opp:58,fit:"Moderate",comp:["UPL","DuPont"],gap:"3-way pre-mix"},
  "Guntur":{prev:65,opp:85,fit:"Strong",comp:["Almix (DuPont)","Sunrice (Dhanuka)"],gap:"Sedge-specific pre-mix"},
  "Srikakulam":{prev:42,opp:52,fit:"Moderate",comp:["Generic"],gap:"Replace generics"},
  "Krishna":{prev:55,opp:72,fit:"Strong",comp:["DuPont","Generic"],gap:"Pre-mix for sedge+grass"},
  "Visakhapatnam":{prev:35,opp:38,fit:"Moderate",comp:["UPL","Bayer"],gap:"Low priority"},
  "Vizianagaram":{prev:38,opp:42,fit:"Moderate",comp:["DuPont","Generic"],gap:"FPO channel"},
  "Kurnool":{prev:40,opp:45,fit:"Moderate",comp:["Generic","DuPont (Low)"],gap:"Affordable solution"},
  "Prakasam":{prev:48,opp:52,fit:"Moderate",comp:["Dhanuka","Generic"],gap:"Sedge management"},
  "Nellore":{prev:30,opp:28,fit:"Weak",comp:["Generic"],gap:"Low incidence"},
  "YSR Kadapa":{prev:58,opp:48,fit:"Moderate",comp:["DuPont (Strong)","Bayer"],gap:"Limited gap"},
  "Chittoor":{prev:28,opp:15,fit:"Weak",comp:["Bayer","UPL"],gap:"Not viable"},
  "Anantapur":{prev:22,opp:10,fit:"Weak",comp:["Bayer","Syngenta"],gap:"None"}
 }},
{id:"PW5",name:"Knotgrass",sci:"Paspalum distichum",type:"Grass",severity:"High",prevalence:52,
 control:"Pretilachlor, Oxadiazon",resistRisk:"Medium",peakStage:"Tillering",controlWindow:"0–20 DAT",
 lossRange:"30–60%",threshold:"8–12 plants/m²",
 distData:{
  "East Godavari":{prev:28,opp:35,fit:"Moderate",comp:["Nominee Gold (UPL)","Ricestar (Bayer)"],gap:"Limited"},
  "West Godavari":{prev:32,opp:38,fit:"Moderate",comp:["UPL","Dow"],gap:"Secondary weed"},
  "Guntur":{prev:38,opp:45,fit:"Moderate",comp:["DuPont","Dhanuka"],gap:"Grass management"},
  "Srikakulam":{prev:30,opp:32,fit:"Weak",comp:["Generic"],gap:"Low priority"},
  "Krishna":{prev:40,opp:48,fit:"Moderate",comp:["DuPont","Generic"],gap:"Grass+sedge complex"},
  "Visakhapatnam":{prev:35,opp:58,fit:"Moderate",comp:["UPL","Bayer"],gap:"Knotgrass-specific"},
  "Vizianagaram":{prev:25,opp:28,fit:"Weak",comp:["DuPont","Generic"],gap:"Not primary"},
  "Kurnool":{prev:35,opp:42,fit:"Moderate",comp:["Generic"],gap:"Affordable grass control"},
  "Prakasam":{prev:42,opp:45,fit:"Moderate",comp:["Dhanuka","Generic"],gap:"Grass management"},
  "Nellore":{prev:48,opp:55,fit:"Moderate",comp:["Dhanuka","Generic"],gap:"Pre-emergent+Post-emergent kit"},
  "YSR Kadapa":{prev:45,opp:35,fit:"Weak",comp:["DuPont","Bayer"],gap:"Strong incumbents"},
  "Chittoor":{prev:60,opp:52,fit:"Moderate",comp:["Bayer","UPL"],gap:"Resistance management"},
  "Anantapur":{prev:55,opp:42,fit:"Moderate",comp:["Bayer","Syngenta"],gap:"Limited differentiation"}
 }},
{id:"PW6",name:"Water Primrose",sci:"Ludwigia octovalvis",type:"Broadleaf",severity:"Medium",prevalence:45,
 control:"2,4-D Amine",resistRisk:"Low",peakStage:"Panicle Initiation",controlWindow:"21–45 DAT",
 lossRange:"10–20%",threshold:"2–4 plants/m²",
 distData:{
  "East Godavari":{prev:35,opp:42,fit:"Moderate",comp:["Weedmar (Dhanuka)","2,4-D (Generic)"],gap:"Targeted solution"},
  "West Godavari":{prev:30,opp:38,fit:"Moderate",comp:["Dhanuka","Generic"],gap:"Broadleaf combo"},
  "Guntur":{prev:22,opp:28,fit:"Weak",comp:["DuPont","Dhanuka"],gap:"Low priority"},
  "Srikakulam":{prev:28,opp:32,fit:"Weak",comp:["Generic"],gap:"Not primary"},
  "Krishna":{prev:38,opp:42,fit:"Moderate",comp:["DuPont","Generic"],gap:"Broadleaf management"},
  "Visakhapatnam":{prev:25,opp:28,fit:"Weak",comp:["UPL","Bayer"],gap:"Low opportunity"},
  "Vizianagaram":{prev:32,opp:38,fit:"Moderate",comp:["DuPont","Generic"],gap:"FPO channel"},
  "Kurnool":{prev:20,opp:22,fit:"Weak",comp:["Generic"],gap:"Price-driven"},
  "Prakasam":{prev:55,opp:65,fit:"Strong",comp:["Dhanuka","Generic"],gap:"Water Primrose targeted"},
  "Nellore":{prev:42,opp:52,fit:"Moderate",comp:["Dhanuka","Generic"],gap:"Broadleaf-specific"},
  "YSR Kadapa":{prev:28,opp:22,fit:"Weak",comp:["DuPont","Bayer"],gap:"Limited"},
  "Chittoor":{prev:35,opp:25,fit:"Weak",comp:["Bayer","UPL"],gap:"Not viable"},
  "Anantapur":{prev:18,opp:12,fit:"Weak",comp:["Bayer","Syngenta"],gap:"None"}
 }}
],
maize_mh:[
{id:"MW1",name:"Purple Nutsedge",sci:"Cyperus rotundus",type:"Sedge",severity:"High",prevalence:82,
 control:"Halosulfuron, Atrazine+Topramezone",resistRisk:"Medium",peakStage:"Early Post-emergence",controlWindow:"15–25 DAS",
 lossRange:"30–70%",threshold:"5–8 plants/m²",
 distData:{
  "Aurangabad":{prev:80,opp:92,fit:"Strong",comp:["Sempra (Bayer)","Halosulfuron (Generic)"],gap:"Nutsedge+Broadleaf pre-mix"},
  "Pune":{prev:65,opp:78,fit:"Strong",comp:["Sempra (Bayer)","Generic"],gap:"Non-Bayer nutsedge solution"},
  "Ahmednagar":{prev:55,opp:72,fit:"Strong",comp:["Syngenta","Generic"],gap:"Broad-spectrum single-shot"},
  "Kolhapur":{prev:48,opp:68,fit:"Strong",comp:["Syngenta (Low)","Generic"],gap:"Modern nutsedge control"},
  "Nashik":{prev:42,opp:62,fit:"Strong",comp:["Bayer","Generic"],gap:"Roundup replacement"},
  "Latur":{prev:45,opp:55,fit:"Moderate",comp:["Syngenta (Strong)","Bayer"],gap:"Bundle pricing needed"},
  "Jalgaon":{prev:38,opp:52,fit:"Moderate",comp:["Generic","Bayer (Low)"],gap:"Modern nutsedge control"},
  "Buldhana":{prev:60,opp:58,fit:"Moderate",comp:["Generic","Syngenta (Low)"],gap:"Affordable nutsedge solution"},
  "Satara":{prev:40,opp:42,fit:"Moderate",comp:["Syngenta","Nissan (Low)"],gap:"Tank-mix replacement"},
  "Sangli":{prev:58,opp:48,fit:"Moderate",comp:["Bayer","Generic"],gap:"Limited differentiation"},
  "Solapur":{prev:25,opp:22,fit:"Weak",comp:["Syngenta (Strong)","Bayer (Strong)"],gap:"Saturated"},
  "Nanded":{prev:35,opp:30,fit:"Weak",comp:["Bayer (Strong)","UPL"],gap:"Soybean-dominant"},
  "Amravati":{prev:28,opp:18,fit:"Weak",comp:["UPL (Strong)","Syngenta"],gap:"Cotton belt"},
  "Nagpur":{prev:22,opp:12,fit:"Weak",comp:["UPL (Strong)","Bayer"],gap:"None"},
  "Beed":{prev:18,opp:10,fit:"Weak",comp:["Syngenta","Generic"],gap:"Drought-prone"}
 }},
{id:"MW2",name:"Bermuda Grass",sci:"Cynodon dactylon",type:"Grass",severity:"High",prevalence:72,
 control:"Atrazine, Tembotrione",resistRisk:"Medium",peakStage:"Vegetative",controlWindow:"10–20 DAS",
 lossRange:"25–55%",threshold:"8–15 plants/m²",
 distData:{
  "Nashik":{prev:68,opp:78,fit:"Strong",comp:["Roundup (Bayer)","Paraquat (Syngenta)"],gap:"Grass-specific modern"},
  "Pune":{prev:42,opp:65,fit:"Strong",comp:["Bayer","Generic"],gap:"Pre-mix for mixed flora"},
  "Ahmednagar":{prev:62,opp:75,fit:"Strong",comp:["Syngenta","Generic"],gap:"Resistance-breaking combo"},
  "Kolhapur":{prev:55,opp:72,fit:"Strong",comp:["Syngenta (Low)","Bayer (Low)"],gap:"Modern Atrazine replacement"},
  "Aurangabad":{prev:45,opp:58,fit:"Moderate",comp:["Bayer","Syngenta"],gap:"Secondary priority"},
  "Latur":{prev:40,opp:48,fit:"Moderate",comp:["Syngenta (Strong)","Bayer"],gap:"Broadleaf complex"},
  "Jalgaon":{prev:50,opp:55,fit:"Moderate",comp:["Generic","Bayer (Low)"],gap:"Grass-specific"},
  "Buldhana":{prev:38,opp:42,fit:"Moderate",comp:["Generic","Syngenta (Low)"],gap:"Distribution needed"},
  "Satara":{prev:58,opp:62,fit:"Moderate",comp:["Syngenta","Nissan (Low)"],gap:"Grass-specific modern"},
  "Sangli":{prev:35,opp:38,fit:"Moderate",comp:["Bayer","Generic"],gap:"Co-marketing"},
  "Solapur":{prev:30,opp:25,fit:"Weak",comp:["Syngenta","Bayer"],gap:"Saturated"},
  "Nanded":{prev:32,opp:28,fit:"Weak",comp:["Bayer","UPL"],gap:"Soybean-dominant"},
  "Amravati":{prev:45,opp:22,fit:"Weak",comp:["UPL","Syngenta"],gap:"Cotton belt"},
  "Nagpur":{prev:25,opp:15,fit:"Weak",comp:["UPL","Bayer"],gap:"None"},
  "Beed":{prev:20,opp:12,fit:"Weak",comp:["Syngenta","Generic"],gap:"Drought-prone"}
 }},
{id:"MW3",name:"Congress Grass",sci:"Parthenium hysterophorus",type:"Broadleaf",severity:"High",prevalence:78,
 control:"Atrazine, 2,4-D",resistRisk:"Low",peakStage:"Vegetative",controlWindow:"15–25 DAS",
 lossRange:"20–45%",threshold:"3–8 plants/m²",
 distData:{
  "Ahmednagar":{prev:72,opp:85,fit:"Strong",comp:["Atrazine (Syngenta)","Laudis (Bayer)"],gap:"Resistance-breaking combo"},
  "Kolhapur":{prev:75,opp:88,fit:"Strong",comp:["Syngenta (Low)","Bayer (Low)"],gap:"Post-emergent combo"},
  "Aurangabad":{prev:58,opp:78,fit:"Strong",comp:["Sempra (Bayer)","Atrazine (Syngenta)"],gap:"Congress Grass focused"},
  "Nashik":{prev:45,opp:62,fit:"Strong",comp:["Bayer","Generic"],gap:"Broadleaf-specific modern"},
  "Pune":{prev:50,opp:68,fit:"Strong",comp:["Bayer","Generic"],gap:"Urban-adjacent progressive"},
  "Latur":{prev:68,opp:72,fit:"Strong",comp:["Syngenta (Strong)","Bayer"],gap:"Broadleaf complex pre-mix"},
  "Jalgaon":{prev:40,opp:48,fit:"Moderate",comp:["Generic","Bayer (Low)"],gap:"Modern broadleaf control"},
  "Buldhana":{prev:40,opp:45,fit:"Moderate",comp:["Generic","Syngenta (Low)"],gap:"Awareness campaigns"},
  "Satara":{prev:35,opp:38,fit:"Moderate",comp:["Syngenta","Nissan (Low)"],gap:"Grass-heavy area"},
  "Sangli":{prev:42,opp:40,fit:"Moderate",comp:["Bayer","Generic"],gap:"Co-marketing"},
  "Solapur":{prev:28,opp:22,fit:"Weak",comp:["Syngenta","Bayer"],gap:"Low area"},
  "Nanded":{prev:48,opp:38,fit:"Weak",comp:["Bayer","UPL"],gap:"Soybean-dominant"},
  "Amravati":{prev:35,opp:18,fit:"Weak",comp:["UPL","Syngenta"],gap:"Cotton belt"},
  "Nagpur":{prev:30,opp:12,fit:"Weak",comp:["UPL","Bayer"],gap:"None"},
  "Beed":{prev:22,opp:10,fit:"Weak",comp:["Syngenta","Generic"],gap:"Minimal"}
 }},
{id:"MW4",name:"Pigweed",sci:"Amaranthus viridis",type:"Broadleaf",severity:"Medium",prevalence:55,
 control:"Atrazine, Topramezone",resistRisk:"Low",peakStage:"Vegetative",controlWindow:"10–20 DAS",
 lossRange:"15–30%",threshold:"5–12 plants/m²",
 distData:{
  "Jalgaon":{prev:58,opp:68,fit:"Strong",comp:["Atrazine (Generic)","Laudis (Bayer)"],gap:"Pigweed pre-mix"},
  "Aurangabad":{prev:42,opp:55,fit:"Moderate",comp:["Bayer","Syngenta"],gap:"Broadleaf complex"},
  "Latur":{prev:45,opp:52,fit:"Moderate",comp:["Syngenta (Strong)","Bayer"],gap:"Pigweed targeted"},
  "Nanded":{prev:52,opp:58,fit:"Moderate",comp:["Bayer","UPL"],gap:"Pigweed pre-mix"},
  "Ahmednagar":{prev:38,opp:45,fit:"Moderate",comp:["Syngenta","Generic"],gap:"Broad-spectrum"},
  "Kolhapur":{prev:40,opp:42,fit:"Moderate",comp:["Syngenta (Low)","Bayer (Low)"],gap:"Modern control"},
  "Pune":{prev:35,opp:38,fit:"Moderate",comp:["Bayer","Generic"],gap:"Secondary priority"},
  "Nashik":{prev:30,opp:32,fit:"Weak",comp:["Bayer","Generic"],gap:"Low priority"},
  "Buldhana":{prev:35,opp:38,fit:"Moderate",comp:["Generic","Syngenta (Low)"],gap:"Awareness"},
  "Sangli":{prev:32,opp:30,fit:"Weak",comp:["Bayer","Generic"],gap:"Limited"},
  "Satara":{prev:28,opp:25,fit:"Weak",comp:["Syngenta","Nissan"],gap:"Not primary"},
  "Solapur":{prev:25,opp:18,fit:"Weak",comp:["Syngenta","Bayer"],gap:"Low area"},
  "Amravati":{prev:22,opp:15,fit:"Weak",comp:["UPL","Syngenta"],gap:"Cotton belt"},
  "Nagpur":{prev:20,opp:10,fit:"Weak",comp:["UPL","Bayer"],gap:"None"},
  "Beed":{prev:30,opp:22,fit:"Weak",comp:["Syngenta","Generic"],gap:"Drought-prone"}
 }},
{id:"MW5",name:"Goosegrass",sci:"Eleusine indica",type:"Grass",severity:"Medium",prevalence:48,
 control:"Tembotrione, Topramezone",resistRisk:"Medium",peakStage:"Vegetative",controlWindow:"12–22 DAS",
 lossRange:"15–35%",threshold:"10–15 plants/m²",
 distData:{
  "Amravati":{prev:48,opp:52,fit:"Moderate",comp:["Targa Super (Nissan)","Fusilade (Syngenta)"],gap:"Grass-specific herbicide"},
  "Nagpur":{prev:55,opp:48,fit:"Moderate",comp:["UPL","Bayer"],gap:"Grass control"},
  "Satara":{prev:40,opp:45,fit:"Moderate",comp:["Syngenta","Nissan (Low)"],gap:"Modern grass control"},
  "Ahmednagar":{prev:35,opp:40,fit:"Moderate",comp:["Syngenta","Generic"],gap:"Grass management"},
  "Nashik":{prev:38,opp:42,fit:"Moderate",comp:["Bayer","Generic"],gap:"Grass-specific modern"},
  "Kolhapur":{prev:32,opp:38,fit:"Moderate",comp:["Syngenta (Low)","Bayer (Low)"],gap:"Modern solution"},
  "Pune":{prev:28,opp:32,fit:"Weak",comp:["Bayer","Generic"],gap:"Secondary target"},
  "Aurangabad":{prev:30,opp:28,fit:"Weak",comp:["Bayer","Syngenta"],gap:"Low priority"},
  "Latur":{prev:35,opp:32,fit:"Weak",comp:["Syngenta","Bayer"],gap:"Broadleaf focus area"},
  "Jalgaon":{prev:25,opp:22,fit:"Weak",comp:["Generic","Bayer (Low)"],gap:"Low incidence"},
  "Buldhana":{prev:25,opp:20,fit:"Weak",comp:["Generic"],gap:"Not primary"},
  "Sangli":{prev:28,opp:22,fit:"Weak",comp:["Bayer","Generic"],gap:"Limited"},
  "Nanded":{prev:30,opp:25,fit:"Weak",comp:["Bayer","UPL"],gap:"Soybean-dominant"},
  "Solapur":{prev:22,opp:15,fit:"Weak",comp:["Syngenta","Bayer"],gap:"Low area"},
  "Beed":{prev:18,opp:10,fit:"Weak",comp:["Syngenta","Generic"],gap:"Minimal"}
 }},
{id:"MW6",name:"Common Purslane",sci:"Portulaca oleracea",type:"Broadleaf",severity:"Low",prevalence:38,
 control:"Atrazine, 2,4-D",resistRisk:"Low",peakStage:"Vegetative",controlWindow:"10–20 DAS",
 lossRange:"5–15%",threshold:"15–25 plants/m²",
 distData:{
  "Solapur":{prev:42,opp:48,fit:"Moderate",comp:["Dual Gold (Syngenta)","Atrazine (Generic)"],gap:"Broadleaf-specific"},
  "Beed":{prev:45,opp:42,fit:"Moderate",comp:["Syngenta","Generic"],gap:"Drought-adapted weed"},
  "Amravati":{prev:35,opp:32,fit:"Weak",comp:["UPL","Syngenta"],gap:"Cotton belt"},
  "Jalgaon":{prev:30,opp:28,fit:"Weak",comp:["Generic","Bayer (Low)"],gap:"Low priority"},
  "Satara":{prev:28,opp:25,fit:"Weak",comp:["Syngenta","Nissan"],gap:"Secondary weed"},
  "Pune":{prev:22,opp:20,fit:"Weak",comp:["Bayer","Generic"],gap:"Low incidence"},
  "Nashik":{prev:25,opp:22,fit:"Weak",comp:["Bayer","Generic"],gap:"Not priority"},
  "Aurangabad":{prev:20,opp:18,fit:"Weak",comp:["Bayer","Syngenta"],gap:"Low incidence"},
  "Ahmednagar":{prev:15,opp:12,fit:"Weak",comp:["Syngenta","Generic"],gap:"Minimal"},
  "Kolhapur":{prev:18,opp:15,fit:"Weak",comp:["Syngenta","Bayer"],gap:"Not primary"},
  "Sangli":{prev:20,opp:15,fit:"Weak",comp:["Bayer","Generic"],gap:"Limited"},
  "Buldhana":{prev:20,opp:12,fit:"Weak",comp:["Generic"],gap:"Not primary"},
  "Latur":{prev:22,opp:18,fit:"Weak",comp:["Syngenta","Bayer"],gap:"Low priority"},
  "Nanded":{prev:25,opp:15,fit:"Weak",comp:["Bayer","UPL"],gap:"None"},
  "Nagpur":{prev:18,opp:10,fit:"Weak",comp:["UPL","Bayer"],gap:"None"}
 }}
]
};

var PL_DATA={paddy_ap:{
scenario:{crop:"Paddy",product:"InficusPre-Mix 360 SC",targetWeeds:["Barnyard Grass","Variable Flatsedge","Globe Fimbry"],geography:"Andhra Pradesh"},
districts:[
{name:"East Godavari",unmetOpp:92,compIntensity:75,marketPot:18.5,productFit:"Strong",topWeeds:["Barnyard Grass","Variable Flatsedge","Pickerelweed"],competitors:["Nominee Gold (UPL)","Clincher (Dow)","Almix (DuPont)"],estPotCr:4.2,compShare:{UPL:35,Syngenta:20,DuPont:15,Generic:30},molecules:{Pretilachlor:40,Bispyribac:25,Pyrazosulfuron:20,"2,4-D":15},gaps:["Pre-mix (Pretilachlor+Bispyribac)","Sedge+Broadleaf combo"],wave:1,waveReason:"Highest unmet opp + strong product fit; UPL dominance showing weed escape signals"},
{name:"West Godavari",unmetOpp:88,compIntensity:70,marketPot:16.2,productFit:"Strong",topWeeds:["Barnyard Grass","Pickerelweed","Variable Flatsedge"],competitors:["Nominee Gold (UPL)","Clincher (Dow)"],estPotCr:3.8,compShare:{UPL:38,Dow:18,Generic:44},molecules:{Pretilachlor:35,Cyhalofop:22,Bispyribac:28,"2,4-D":15},gaps:["3-way pre-mix","Post-emergent combo"],wave:1,waveReason:"High farmer dissatisfaction with UPL; strong conversion opportunity"},
{name:"Guntur",unmetOpp:82,compIntensity:45,marketPot:14.8,productFit:"Strong",topWeeds:["Globe Fimbry","Variable Flatsedge","Barnyard Grass"],competitors:["Almix (DuPont)","Sunrice (Dhanuka)"],estPotCr:3.5,compShare:{DuPont:30,Dhanuka:15,Generic:55},molecules:{Pyrazosulfuron:45,Pretilachlor:25,Bensulfuron:18,"2,4-D":12},gaps:["Sedge-specific pre-mix","Broad-spectrum single shot"],wave:1,waveReason:"Low competition; high sedge pressure creates clear product positioning"},
{name:"Srikakulam",unmetOpp:78,compIntensity:40,marketPot:10.5,productFit:"Strong",topWeeds:["Barnyard Grass","Variable Flatsedge"],competitors:["Nominee Gold (UPL)","Generic"],estPotCr:2.4,compShare:{UPL:25,Generic:65,Others:10},molecules:{Pretilachlor:50,Bispyribac:20,"2,4-D":18,Butachlor:12},gaps:["Modern pre-mix replacement for Butachlor","Resistance-breaking combo"],wave:1,waveReason:"Generic-dominated; easy displacement with efficacy demos"},
{name:"Krishna",unmetOpp:75,compIntensity:48,marketPot:13.2,productFit:"Strong",topWeeds:["Variable Flatsedge","Globe Fimbry","Barnyard Grass"],competitors:["Almix (DuPont)","Generic"],estPotCr:3.1,compShare:{DuPont:28,Generic:52,Others:20},molecules:{Pyrazosulfuron:38,Pretilachlor:30,Bensulfuron:18,"2,4-D":14},gaps:["Pre-mix for sedge+grass complex","Tank-mix replacement"],wave:1,waveReason:"Strong sedge problem; DuPont losing share to generics"},
{name:"Visakhapatnam",unmetOpp:65,compIntensity:62,marketPot:12.8,productFit:"Moderate",topWeeds:["Barnyard Grass","Knotgrass"],competitors:["Nominee Gold (UPL)","Ricestar (Bayer)"],estPotCr:2.8,compShare:{UPL:32,Bayer:22,Syngenta:15,Generic:31},molecules:{Pretilachlor:35,Bispyribac:28,Cyhalofop:22,"2,4-D":15},gaps:["Knotgrass-specific solution","Resistance management pre-mix"],wave:2,waveReason:"Moderate opportunity; needs differentiation vs Bayer"},
{name:"Vizianagaram",unmetOpp:58,compIntensity:42,marketPot:7.5,productFit:"Moderate",topWeeds:["Variable Flatsedge","Pickerelweed"],competitors:["DuPont (Moderate)","Generic"],estPotCr:1.8,compShare:{DuPont:22,Generic:60,Others:18},molecules:{Pyrazosulfuron:40,Pretilachlor:28,"2,4-D":20,Others:12},gaps:["Broadleaf+Sedge combo","FPO-channel specific packs"],wave:2,waveReason:"Generic heavy market; moderate potential with targeted approach"},
{name:"Kurnool",unmetOpp:55,compIntensity:35,marketPot:9.2,productFit:"Moderate",topWeeds:["Variable Flatsedge","Knotgrass"],competitors:["Generic","DuPont (Low)"],estPotCr:2.1,compShare:{DuPont:12,Generic:72,Others:16},molecules:{Pretilachlor:45,Pyrazosulfuron:25,"2,4-D":18,Others:12},gaps:["Affordable pre-mix for smallholders","Sedge management solution"],wave:2,waveReason:"Price-sensitive; needs competitive pricing strategy"},
{name:"Prakasam",unmetOpp:52,compIntensity:38,marketPot:8.8,productFit:"Moderate",topWeeds:["Water Primrose","Pickerelweed"],competitors:["Dhanuka (Moderate)","Generic"],estPotCr:2.0,compShare:{Dhanuka:20,Generic:62,Others:18},molecules:{Pretilachlor:35,"2,4-D":30,Metsulfuron:18,Others:17},gaps:["Broadleaf-specific pre-mix","Water Primrose targeted"],wave:2,waveReason:"Broadleaf-dominant; product positioning requires adaptation"},
{name:"Nellore",unmetOpp:42,compIntensity:32,marketPot:7.2,productFit:"Moderate",topWeeds:["Pickerelweed","Knotgrass"],competitors:["Dhanuka (Low)","Generic"],estPotCr:1.6,compShare:{Dhanuka:15,Generic:70,Others:15},molecules:{Pretilachlor:40,"2,4-D":28,Oxadiazon:18,Others:14},gaps:["Pre-emergent+Post-emergent kit","Pickerelweed targeted"],wave:2,waveReason:"Moderate potential; generic displacement opportunity"},
{name:"YSR Kadapa",unmetOpp:35,compIntensity:55,marketPot:5.5,productFit:"Weak",topWeeds:["Globe Fimbry","Water Primrose"],competitors:["DuPont (Strong)","Bayer (Moderate)"],estPotCr:1.2,compShare:{DuPont:35,Bayer:25,Generic:40},molecules:{Pyrazosulfuron:40,Bensulfuron:25,"2,4-D":20,Others:15},gaps:["Limited gap; incumbents strong"],wave:3,waveReason:"Strong incumbents; expansion only after Wave 1-2 success"},
{name:"Chittoor",unmetOpp:25,compIntensity:72,marketPot:4.8,productFit:"Weak",topWeeds:["Knotgrass","Water Primrose"],competitors:["Bayer (Strong)","UPL (Strong)"],estPotCr:0.9,compShare:{Bayer:35,UPL:30,Syngenta:15,Generic:20},molecules:{Cyhalofop:30,Pretilachlor:25,Oxadiazon:25,"2,4-D":20},gaps:["Saturated; no clear gap"],wave:3,waveReason:"High competition; low weed pressure; monitor only"},
{name:"Anantapur",unmetOpp:20,compIntensity:68,marketPot:3.2,productFit:"Weak",topWeeds:["Knotgrass","Water Primrose"],competitors:["Bayer (Strong)","Syngenta (Moderate)"],estPotCr:0.6,compShare:{Bayer:32,Syngenta:28,Generic:40},molecules:{Pretilachlor:30,Oxadiazon:28,"2,4-D":22,Others:20},gaps:["Minimal; paddy not primary"],wave:3,waveReason:"Paddy negligible; not strategic for launch"}
],
stageGates:{regulatory:"High",supply:"High",distributor:"Medium"},
impact:{totalPotCr:23.8,wave1Cr:17.0,wave2Cr:10.3,wave3Cr:2.7,districtsTargeted:13,wave1Count:5,wave2Count:5,wave3Count:3}
},
maize_mh:{
scenario:{crop:"Maize",product:"InficusMaize Pro 450 SC",targetWeeds:["Purple Nutsedge","Congress Grass","Bermuda Grass"],geography:"Maharashtra"},
districts:[
{name:"Aurangabad",unmetOpp:90,compIntensity:65,marketPot:17.5,productFit:"Strong",topWeeds:["Purple Nutsedge","Congress Grass","Bermuda Grass"],competitors:["Sempra (Bayer)","Atrazine (Syngenta)"],estPotCr:4.0,compShare:{Bayer:30,Syngenta:25,Generic:45},molecules:{Atrazine:35,Halosulfuron:25,Tembotrione:20,"2,4-D":20},gaps:["Nutsedge+Broadleaf pre-mix","Topramezone combo"],wave:1,waveReason:"Highest nutsedge pressure; Bayer losing satisfaction scores"},
{name:"Kolhapur",unmetOpp:85,compIntensity:35,marketPot:12.8,productFit:"Strong",topWeeds:["Congress Grass","Bermuda Grass"],competitors:["Syngenta (Low)","Bayer (Low)"],estPotCr:3.2,compShare:{Syngenta:18,Bayer:12,Generic:70},molecules:{Atrazine:50,"2,4-D":25,Tembotrione:15,Others:10},gaps:["Post-emergent grass+broadleaf combo","Modern Atrazine replacement"],wave:1,waveReason:"Minimal competition; generic-dominated with high weed pressure"},
{name:"Ahmednagar",unmetOpp:80,compIntensity:48,marketPot:14.2,productFit:"Strong",topWeeds:["Congress Grass","Bermuda Grass","Purple Nutsedge"],competitors:["Syngenta (Moderate)","Generic"],estPotCr:3.5,compShare:{Syngenta:28,Generic:55,Others:17},molecules:{Atrazine:42,Tembotrione:22,"2,4-D":20,Halosulfuron:16},gaps:["Broad-spectrum single-shot","Resistance-breaking combo"],wave:1,waveReason:"High Congress Grass; Syngenta Atrazine showing resistance signals"},
{name:"Pune",unmetOpp:76,compIntensity:68,marketPot:15.5,productFit:"Strong",topWeeds:["Purple Nutsedge","Bermuda Grass"],competitors:["Sempra (Bayer)","Roundup (Bayer)"],estPotCr:3.6,compShare:{Bayer:38,Syngenta:20,Generic:42},molecules:{Halosulfuron:30,Atrazine:28,Tembotrione:22,"2,4-D":20},gaps:["Non-Bayer nutsedge solution","Pre-mix for mixed weed flora"],wave:1,waveReason:"Large market; Bayer monopoly creates displacement opportunity"},
{name:"Nashik",unmetOpp:72,compIntensity:52,marketPot:13.2,productFit:"Strong",topWeeds:["Bermuda Grass","Purple Nutsedge"],competitors:["Bayer (Moderate)","Generic"],estPotCr:3.0,compShare:{Bayer:28,Generic:55,Others:17},molecules:{Atrazine:38,Tembotrione:25,Halosulfuron:20,"2,4-D":17},gaps:["Grass-specific modern solution","Roundup replacement"],wave:1,waveReason:"Bermuda Grass dominant; farmers seeking non-Roundup alternatives"},
{name:"Latur",unmetOpp:62,compIntensity:55,marketPot:9.8,productFit:"Moderate",topWeeds:["Congress Grass","Pigweed"],competitors:["Syngenta (Strong)","Bayer (Moderate)"],estPotCr:2.2,compShare:{Syngenta:32,Bayer:22,Generic:46},molecules:{Atrazine:40,"2,4-D":28,Topramezone:18,Others:14},gaps:["Broadleaf complex pre-mix","Pigweed targeted"],wave:2,waveReason:"Moderate opportunity; needs differentiation from Syngenta Atrazine"},
{name:"Jalgaon",unmetOpp:58,compIntensity:30,marketPot:8.2,productFit:"Moderate",topWeeds:["Pigweed","Purple Nutsedge"],competitors:["Generic","Bayer (Low)"],estPotCr:1.9,compShare:{Bayer:12,Generic:75,Others:13},molecules:{Atrazine:48,"2,4-D":25,Others:27},gaps:["Modern broadleaf control","Pigweed pre-mix"],wave:2,waveReason:"Generic-heavy; easy entry with efficacy positioning"},
{name:"Buldhana",unmetOpp:55,compIntensity:28,marketPot:6.5,productFit:"Moderate",topWeeds:["Purple Nutsedge","Congress Grass"],competitors:["Generic","Syngenta (Low)"],estPotCr:1.5,compShare:{Syngenta:15,Generic:72,Others:13},molecules:{Atrazine:52,"2,4-D":22,Halosulfuron:15,Others:11},gaps:["Affordable nutsedge solution","Smallholder packs"],wave:2,waveReason:"Low competition; needs distribution build-up"},
{name:"Satara",unmetOpp:52,compIntensity:45,marketPot:7.5,productFit:"Moderate",topWeeds:["Bermuda Grass","Goosegrass"],competitors:["Syngenta (Moderate)","Nissan (Low)"],estPotCr:1.7,compShare:{Syngenta:25,Nissan:10,Generic:65},molecules:{Atrazine:40,Tembotrione:25,"2,4-D":18,Others:17},gaps:["Grass-specific modern herbicide","Tank-mix replacement"],wave:2,waveReason:"Grass-dominant; requires grass-specific positioning"},
{name:"Sangli",unmetOpp:42,compIntensity:48,marketPot:6.8,productFit:"Moderate",topWeeds:["Purple Nutsedge","Bermuda Grass"],competitors:["Bayer (Moderate)","Generic"],estPotCr:1.5,compShare:{Bayer:25,Generic:55,Others:20},molecules:{Halosulfuron:28,Atrazine:35,"2,4-D":22,Others:15},gaps:["Limited differentiation possible"],wave:2,waveReason:"Moderate potential; co-marketing with dealer network"},
{name:"Solapur",unmetOpp:28,compIntensity:65,marketPot:4.2,productFit:"Weak",topWeeds:["Common Purslane","Goosegrass"],competitors:["Syngenta (Strong)","Bayer (Strong)"],estPotCr:0.8,compShare:{Syngenta:30,Bayer:28,Generic:42},molecules:{Atrazine:40,"2,4-D":28,Others:32},gaps:["Saturated market"],wave:3,waveReason:"Low maize area; strong incumbents"},
{name:"Nanded",unmetOpp:38,compIntensity:58,marketPot:5.5,productFit:"Weak",topWeeds:["Pigweed","Goosegrass"],competitors:["Bayer (Strong)","UPL (Moderate)"],estPotCr:1.0,compShare:{Bayer:30,UPL:20,Generic:50},molecules:{Atrazine:42,"2,4-D":25,Tembotrione:18,Others:15},gaps:["Limited; soybean-dominant"],wave:3,waveReason:"Soybean primary; maize secondary crop"},
{name:"Amravati",unmetOpp:22,compIntensity:62,marketPot:3.8,productFit:"Weak",topWeeds:["Goosegrass","Common Purslane"],competitors:["UPL (Strong)","Syngenta (Moderate)"],estPotCr:0.7,compShare:{UPL:28,Syngenta:22,Generic:50},molecules:{Atrazine:38,"2,4-D":30,Others:32},gaps:["None significant"],wave:3,waveReason:"Cotton belt; maize minor"},
{name:"Nagpur",unmetOpp:18,compIntensity:72,marketPot:3.2,productFit:"Weak",topWeeds:["Goosegrass","Common Purslane"],competitors:["UPL (Strong)","Bayer (Strong)"],estPotCr:0.5,compShare:{UPL:32,Bayer:28,Generic:40},molecules:{Atrazine:35,"2,4-D":28,Others:37},gaps:["None"],wave:3,waveReason:"No strategic value for maize"},
{name:"Beed",unmetOpp:15,compIntensity:60,marketPot:2.5,productFit:"Weak",topWeeds:["Common Purslane","Pigweed"],competitors:["Syngenta (Strong)","Generic"],estPotCr:0.4,compShare:{Syngenta:30,Generic:55,Others:15},molecules:{Atrazine:45,"2,4-D":30,Others:25},gaps:["None"],wave:3,waveReason:"Drought-prone; minimal maize"}
],
stageGates:{regulatory:"High",supply:"Medium",distributor:"Medium"},
impact:{totalPotCr:19.7,wave1Cr:17.3,wave2Cr:9.8,wave3Cr:3.4,districtsTargeted:15,wave1Count:5,wave2Count:5,wave3Count:5}
}};
