var SEG_DATA={
paddy_ap:{
tiers:{
tier1:{label:"Tier 1 \u2014 Easy to Win",potential:12.5,color:"#6abf7b",severity:"High",districts:["East Godavari","West Godavari","Guntur","Krishna","Srikakulam"],weedPressure:"Very High",farmerAwareness:"High",productFit:"Strong"},
tier2:{label:"Tier 2 \u2014 Competitive",potential:8.2,color:"#e8b84b",severity:"Medium",districts:["Visakhapatnam","Vizianagaram","Prakasam","Nellore","Kurnool"],weedPressure:"Moderate",farmerAwareness:"Medium",productFit:"Moderate"},
tier3:{label:"Tier 3 \u2014 No Go",potential:3.1,color:"#e05c5c",severity:"Low",districts:["Chittoor","Anantapur","YSR Kadapa"],weedPressure:"Low",farmerAwareness:"Low",productFit:"Weak"}
},
districts:[
{name:"East Godavari",tier:"Tier 1",segment:"Easy to Win",weeds:"Barnyard Grass, Variable Flatsedge",competitor:"UPL (Strong), Syngenta (Moderate)",targetArea:82,compStrength:"Strong",farmerSat:"Medium",convOpp:"Weed escape issues",intel:{targetWeed:"Barnyard Grass",weedSev:"High",controlDiff:"Medium",prodFit:"Strong",recommendations:"Focus on Pretilachlor-based solutions; demonstrate efficacy vs Nominee Gold"}},
{name:"West Godavari",tier:"Tier 1",segment:"Easy to Win",weeds:"Barnyard Grass, Pickerelweed",competitor:"UPL (Strong), Dow (Moderate)",targetArea:78,compStrength:"Strong",farmerSat:"Low",convOpp:"Ineffective control",intel:{targetWeed:"Barnyard Grass",weedSev:"High",controlDiff:"High",prodFit:"Strong",recommendations:"Target farmers dissatisfied with UPL products; emphasize broad-spectrum control"}},
{name:"Guntur",tier:"Tier 1",segment:"Easy to Win",weeds:"Globe Fimbry, Variable Flatsedge",competitor:"DuPont (Moderate), Dhanuka (Low)",targetArea:75,compStrength:"Moderate",farmerSat:"Medium",convOpp:"Strong product fit",intel:{targetWeed:"Globe Fimbry",weedSev:"High",controlDiff:"Medium",prodFit:"Strong",recommendations:"Leverage sedge-specific positioning; FPO channel preferred"}},
{name:"Krishna",tier:"Tier 1",segment:"Easy to Win",weeds:"Variable Flatsedge, Globe Fimbry",competitor:"DuPont (Moderate), Generic (Low)",targetArea:72,compStrength:"Moderate",farmerSat:"Medium",convOpp:"Strong product fit",intel:{targetWeed:"Variable Flatsedge",weedSev:"High",controlDiff:"Low",prodFit:"Strong",recommendations:"Easy conversion from generic products; price-sensitive market"}},
{name:"Srikakulam",tier:"Tier 1",segment:"Easy to Win",weeds:"Barnyard Grass, Variable Flatsedge",competitor:"UPL (Moderate), Generic (High)",targetArea:70,compStrength:"Moderate",farmerSat:"Low",convOpp:"Weed escape issues",intel:{targetWeed:"Barnyard Grass",weedSev:"High",controlDiff:"Medium",prodFit:"Strong",recommendations:"Replace generic products; demo-driven conversion strategy"}},
{name:"Visakhapatnam",tier:"Tier 2",segment:"Competitive",weeds:"Barnyard Grass, Knotgrass",competitor:"UPL (Strong), Bayer (Moderate)",targetArea:62,compStrength:"Moderate",farmerSat:"High",convOpp:"Ineffective control",intel:{targetWeed:"Barnyard Grass",weedSev:"Medium",controlDiff:"Medium",prodFit:"Moderate",recommendations:"Target niche segments where UPL underperforms; focus on knotgrass control"}},
{name:"Vizianagaram",tier:"Tier 2",segment:"Competitive",weeds:"Variable Flatsedge, Pickerelweed",competitor:"DuPont (Moderate), Generic (Moderate)",targetArea:55,compStrength:"Moderate",farmerSat:"Medium",convOpp:"Strong product fit",intel:{targetWeed:"Variable Flatsedge",weedSev:"Medium",controlDiff:"Low",prodFit:"Moderate",recommendations:"Build awareness through FPO partnerships; price competitive entry"}},
{name:"Prakasam",tier:"Tier 2",segment:"Competitive",weeds:"Water Primrose, Pickerelweed",competitor:"Dhanuka (Moderate), Generic (High)",targetArea:52,compStrength:"Moderate",farmerSat:"Medium",convOpp:"Weed escape issues",intel:{targetWeed:"Water Primrose",weedSev:"Medium",controlDiff:"Medium",prodFit:"Moderate",recommendations:"Broadleaf-specific positioning; replace generic 2,4-D usage"}},
{name:"Nellore",tier:"Tier 2",segment:"Competitive",weeds:"Pickerelweed, Knotgrass",competitor:"Dhanuka (Low), Generic (High)",targetArea:50,compStrength:"Low",farmerSat:"Low",convOpp:"Ineffective control",intel:{targetWeed:"Pickerelweed",weedSev:"Medium",controlDiff:"Low",prodFit:"Moderate",recommendations:"Easy displacement of generics; focus on efficacy demonstrations"}},
{name:"Kurnool",tier:"Tier 2",segment:"Competitive",weeds:"Variable Flatsedge, Knotgrass",competitor:"Generic (High), DuPont (Low)",targetArea:48,compStrength:"Low",farmerSat:"Low",convOpp:"Strong product fit",intel:{targetWeed:"Variable Flatsedge",weedSev:"Medium",controlDiff:"Low",prodFit:"Moderate",recommendations:"Price-driven market; bundle offers with sedge control products"}},
{name:"Chittoor",tier:"Tier 3",segment:"No Go",weeds:"Knotgrass, Water Primrose",competitor:"Bayer (Strong), UPL (Strong)",targetArea:32,compStrength:"Strong",farmerSat:"High",convOpp:"Limited",intel:{targetWeed:"Knotgrass",weedSev:"Low",controlDiff:"High",prodFit:"Weak",recommendations:"Monitor only; strong incumbent presence makes entry unviable currently"}},
{name:"Anantapur",tier:"Tier 3",segment:"No Go",weeds:"Knotgrass, Water Primrose",competitor:"Bayer (Strong), Syngenta (Moderate)",targetArea:28,compStrength:"Strong",farmerSat:"High",convOpp:"Limited",intel:{targetWeed:"Knotgrass",weedSev:"Low",controlDiff:"High",prodFit:"Weak",recommendations:"Low weed pressure area; paddy not primary crop — deprioritize"}},
{name:"YSR Kadapa",tier:"Tier 3",segment:"No Go",weeds:"Globe Fimbry, Water Primrose",competitor:"DuPont (Strong), Bayer (Moderate)",targetArea:25,compStrength:"Strong",farmerSat:"High",convOpp:"Limited",intel:{targetWeed:"Globe Fimbry",weedSev:"Low",controlDiff:"High",prodFit:"Weak",recommendations:"Dry zone with limited paddy; not strategic for current season"}}
],
floraMatrix:[
{name:"East Godavari","Barnyard Grass":"High","Variable Flatsedge":"Medium","Pickerelweed":"Medium","Globe Fimbry":"Medium","Knotgrass":"Low","Water Primrose":"Low"},
{name:"West Godavari","Barnyard Grass":"High","Variable Flatsedge":"Medium","Pickerelweed":"Medium","Globe Fimbry":"Medium","Knotgrass":"Low","Water Primrose":"Low"},
{name:"Guntur","Barnyard Grass":"Medium","Variable Flatsedge":"Medium","Pickerelweed":"Medium","Globe Fimbry":"High","Knotgrass":"Medium","Water Primrose":"Low"},
{name:"Krishna","Barnyard Grass":"Medium","Variable Flatsedge":"High","Pickerelweed":"Low","Globe Fimbry":"Medium","Knotgrass":"Medium","Water Primrose":"Medium"},
{name:"Srikakulam","Barnyard Grass":"High","Variable Flatsedge":"Medium","Pickerelweed":"Medium","Globe Fimbry":"Medium","Knotgrass":"Low","Water Primrose":"Low"},
{name:"Visakhapatnam","Barnyard Grass":"High","Variable Flatsedge":"Medium","Pickerelweed":"Medium","Globe Fimbry":"Low","Knotgrass":"Medium","Water Primrose":"Low"},
{name:"Vizianagaram","Barnyard Grass":"Medium","Variable Flatsedge":"High","Pickerelweed":"Medium","Globe Fimbry":"Medium","Knotgrass":"Low","Water Primrose":"Medium"},
{name:"Prakasam","Barnyard Grass":"Low","Variable Flatsedge":"Medium","Pickerelweed":"Medium","Globe Fimbry":"Medium","Knotgrass":"Medium","Water Primrose":"High"},
{name:"Nellore","Barnyard Grass":"Medium","Variable Flatsedge":"Low","Pickerelweed":"High","Globe Fimbry":"Low","Knotgrass":"Medium","Water Primrose":"Medium"},
{name:"Kurnool","Barnyard Grass":"Medium","Variable Flatsedge":"High","Pickerelweed":"Low","Globe Fimbry":"Medium","Knotgrass":"Medium","Water Primrose":"Low"},
{name:"Chittoor","Barnyard Grass":"Low","Variable Flatsedge":"Low","Pickerelweed":"Low","Globe Fimbry":"Low","Knotgrass":"High","Water Primrose":"Medium"},
{name:"Anantapur","Barnyard Grass":"Low","Variable Flatsedge":"Low","Pickerelweed":"Low","Globe Fimbry":"Low","Knotgrass":"Medium","Water Primrose":"Low"},
{name:"YSR Kadapa","Barnyard Grass":"Low","Variable Flatsedge":"Medium","Pickerelweed":"Low","Globe Fimbry":"Medium","Knotgrass":"Medium","Water Primrose":"Low"}
],
compInsights:{farmerSatLow:5,farmerSatMed:5,farmerSatHigh:3,weedEscape:4,ineffective:3,strongFit:4,convTotal:11}
},
maize_mh:{
tiers:{
tier1:{label:"Tier 1 \u2014 Easy to Win",potential:10.8,color:"#6abf7b",severity:"High",districts:["Aurangabad","Pune","Ahmednagar","Kolhapur","Nashik"],weedPressure:"Very High",farmerAwareness:"High",productFit:"Strong"},
tier2:{label:"Tier 2 \u2014 Competitive",potential:6.5,color:"#e8b84b",severity:"Medium",districts:["Latur","Jalgaon","Buldhana","Satara","Sangli"],weedPressure:"Moderate",farmerAwareness:"Medium",productFit:"Moderate"},
tier3:{label:"Tier 3 \u2014 No Go",potential:2.4,color:"#e05c5c",severity:"Low",districts:["Solapur","Nanded","Amravati","Nagpur","Beed"],weedPressure:"Low",farmerAwareness:"Low",productFit:"Weak"}
},
districts:[
{name:"Aurangabad",tier:"Tier 1",segment:"Easy to Win",weeds:"Purple Nutsedge, Congress Grass",competitor:"Bayer (Strong), Syngenta (Moderate)",targetArea:80,compStrength:"Strong",farmerSat:"Low",convOpp:"Weed escape issues",intel:{targetWeed:"Purple Nutsedge",weedSev:"High",controlDiff:"Medium",prodFit:"Strong",recommendations:"Target nutsedge-specific segment; Sempra underperforming in field trials"}},
{name:"Pune",tier:"Tier 1",segment:"Easy to Win",weeds:"Purple Nutsedge, Bermuda Grass",competitor:"Bayer (Strong), Generic (Moderate)",targetArea:75,compStrength:"Strong",farmerSat:"Medium",convOpp:"Strong product fit",intel:{targetWeed:"Purple Nutsedge",weedSev:"Medium",controlDiff:"Low",prodFit:"Strong",recommendations:"Urban-adjacent farming; progressive farmers open to new solutions"}},
{name:"Ahmednagar",tier:"Tier 1",segment:"Easy to Win",weeds:"Congress Grass, Bermuda Grass",competitor:"Syngenta (Moderate), Generic (High)",targetArea:72,compStrength:"Moderate",farmerSat:"Medium",convOpp:"Ineffective control",intel:{targetWeed:"Congress Grass",weedSev:"High",controlDiff:"Medium",prodFit:"Strong",recommendations:"Replace generic Atrazine; demonstrate broad-spectrum efficacy"}},
{name:"Kolhapur",tier:"Tier 1",segment:"Easy to Win",weeds:"Congress Grass, Bermuda Grass",competitor:"Syngenta (Low), Bayer (Low)",targetArea:68,compStrength:"Low",farmerSat:"Low",convOpp:"Strong product fit",intel:{targetWeed:"Congress Grass",weedSev:"High",controlDiff:"Low",prodFit:"Strong",recommendations:"Low competition zone; rapid market capture possible through FPO channel"}},
{name:"Nashik",tier:"Tier 1",segment:"Easy to Win",weeds:"Bermuda Grass, Purple Nutsedge",competitor:"Bayer (Moderate), Generic (High)",targetArea:65,compStrength:"Moderate",farmerSat:"Low",convOpp:"Weed escape issues",intel:{targetWeed:"Bermuda Grass",weedSev:"Medium",controlDiff:"Medium",prodFit:"Strong",recommendations:"Grass-specific positioning; replace Roundup dependency"}},
{name:"Latur",tier:"Tier 2",segment:"Competitive",weeds:"Congress Grass, Pigweed",competitor:"Syngenta (Strong), Bayer (Moderate)",targetArea:58,compStrength:"Moderate",farmerSat:"High",convOpp:"Ineffective control",intel:{targetWeed:"Congress Grass",weedSev:"Medium",controlDiff:"Medium",prodFit:"Moderate",recommendations:"Target broadleaf complex; bundle pricing strategy needed"}},
{name:"Jalgaon",tier:"Tier 2",segment:"Competitive",weeds:"Pigweed, Purple Nutsedge",competitor:"Generic (High), Bayer (Low)",targetArea:52,compStrength:"Low",farmerSat:"Medium",convOpp:"Strong product fit",intel:{targetWeed:"Pigweed",weedSev:"Medium",controlDiff:"Low",prodFit:"Moderate",recommendations:"Generic-dominant market; price-competitive entry with efficacy demo"}},
{name:"Buldhana",tier:"Tier 2",segment:"Competitive",weeds:"Purple Nutsedge, Congress Grass",competitor:"Generic (High), Syngenta (Low)",targetArea:50,compStrength:"Low",farmerSat:"Low",convOpp:"Weed escape issues",intel:{targetWeed:"Purple Nutsedge",weedSev:"Medium",controlDiff:"Medium",prodFit:"Moderate",recommendations:"Transition from generics; awareness campaigns needed"}},
{name:"Satara",tier:"Tier 2",segment:"Competitive",weeds:"Bermuda Grass, Goosegrass",competitor:"Syngenta (Moderate), Nissan (Low)",targetArea:48,compStrength:"Moderate",farmerSat:"Medium",convOpp:"Ineffective control",intel:{targetWeed:"Bermuda Grass",weedSev:"Medium",controlDiff:"Medium",prodFit:"Moderate",recommendations:"Grass-heavy area; Tembotrione-based approach recommended"}},
{name:"Sangli",tier:"Tier 2",segment:"Competitive",weeds:"Purple Nutsedge, Bermuda Grass",competitor:"Bayer (Moderate), Generic (Moderate)",targetArea:45,compStrength:"Moderate",farmerSat:"Medium",convOpp:"Strong product fit",intel:{targetWeed:"Purple Nutsedge",weedSev:"Medium",controlDiff:"Low",prodFit:"Moderate",recommendations:"Moderate opportunity; co-marketing with dealer network"}},
{name:"Solapur",tier:"Tier 3",segment:"No Go",weeds:"Common Purslane, Goosegrass",competitor:"Syngenta (Strong), Bayer (Strong)",targetArea:30,compStrength:"Strong",farmerSat:"High",convOpp:"Limited",intel:{targetWeed:"Common Purslane",weedSev:"Low",controlDiff:"High",prodFit:"Weak",recommendations:"Low maize area; strong incumbents; deprioritize"}},
{name:"Nanded",tier:"Tier 3",segment:"No Go",weeds:"Pigweed, Goosegrass",competitor:"Bayer (Strong), UPL (Moderate)",targetArea:28,compStrength:"Strong",farmerSat:"High",convOpp:"Limited",intel:{targetWeed:"Pigweed",weedSev:"Low",controlDiff:"High",prodFit:"Weak",recommendations:"Soybean-dominant region; maize secondary crop — skip"}},
{name:"Amravati",tier:"Tier 3",segment:"No Go",weeds:"Goosegrass, Common Purslane",competitor:"UPL (Strong), Syngenta (Moderate)",targetArea:25,compStrength:"Strong",farmerSat:"High",convOpp:"Limited",intel:{targetWeed:"Goosegrass",weedSev:"Low",controlDiff:"High",prodFit:"Weak",recommendations:"Cotton belt; maize minor crop; no strategic value"}},
{name:"Nagpur",tier:"Tier 3",segment:"No Go",weeds:"Goosegrass, Common Purslane",competitor:"UPL (Strong), Bayer (Strong)",targetArea:22,compStrength:"Strong",farmerSat:"High",convOpp:"Limited",intel:{targetWeed:"Goosegrass",weedSev:"Low",controlDiff:"High",prodFit:"Weak",recommendations:"Orange/cotton region; maize negligible — no entry"}},
{name:"Beed",tier:"Tier 3",segment:"No Go",weeds:"Common Purslane, Pigweed",competitor:"Syngenta (Strong), Generic (Moderate)",targetArea:20,compStrength:"Strong",farmerSat:"High",convOpp:"Limited",intel:{targetWeed:"Common Purslane",weedSev:"Low",controlDiff:"High",prodFit:"Weak",recommendations:"Drought-prone; low weed pressure; not viable for maize herbicides"}}
],
floraMatrix:[
{name:"Aurangabad","Purple Nutsedge":"High","Bermuda Grass":"Medium","Congress Grass":"Medium","Pigweed":"Medium","Goosegrass":"Low","Common Purslane":"Low"},
{name:"Pune","Purple Nutsedge":"High","Bermuda Grass":"Medium","Congress Grass":"Medium","Pigweed":"Low","Goosegrass":"Low","Common Purslane":"Low"},
{name:"Ahmednagar","Purple Nutsedge":"Medium","Bermuda Grass":"High","Congress Grass":"High","Pigweed":"Medium","Goosegrass":"Medium","Common Purslane":"Low"},
{name:"Kolhapur","Purple Nutsedge":"Medium","Bermuda Grass":"Medium","Congress Grass":"High","Pigweed":"Medium","Goosegrass":"Medium","Common Purslane":"Low"},
{name:"Nashik","Purple Nutsedge":"Medium","Bermuda Grass":"High","Congress Grass":"Medium","Pigweed":"Low","Goosegrass":"Medium","Common Purslane":"Low"},
{name:"Latur","Purple Nutsedge":"Medium","Bermuda Grass":"Medium","Congress Grass":"High","Pigweed":"Medium","Goosegrass":"Medium","Common Purslane":"Low"},
{name:"Jalgaon","Purple Nutsedge":"Medium","Bermuda Grass":"Medium","Congress Grass":"Medium","Pigweed":"High","Goosegrass":"Low","Common Purslane":"Medium"},
{name:"Buldhana","Purple Nutsedge":"High","Bermuda Grass":"Medium","Congress Grass":"Medium","Pigweed":"Medium","Goosegrass":"Low","Common Purslane":"Low"},
{name:"Satara","Purple Nutsedge":"Medium","Bermuda Grass":"High","Congress Grass":"Low","Pigweed":"Low","Goosegrass":"Medium","Common Purslane":"Medium"},
{name:"Sangli","Purple Nutsedge":"High","Bermuda Grass":"Low","Congress Grass":"Medium","Pigweed":"Medium","Goosegrass":"Low","Common Purslane":"Low"},
{name:"Solapur","Purple Nutsedge":"Low","Bermuda Grass":"Low","Congress Grass":"Low","Pigweed":"Low","Goosegrass":"Low","Common Purslane":"High"},
{name:"Nanded","Purple Nutsedge":"Low","Bermuda Grass":"Low","Congress Grass":"Medium","Pigweed":"Medium","Goosegrass":"Low","Common Purslane":"Low"},
{name:"Amravati","Purple Nutsedge":"Low","Bermuda Grass":"Medium","Congress Grass":"Low","Pigweed":"Low","Goosegrass":"High","Common Purslane":"Medium"},
{name:"Nagpur","Purple Nutsedge":"Low","Bermuda Grass":"Low","Congress Grass":"Low","Pigweed":"Low","Goosegrass":"High","Common Purslane":"Low"},
{name:"Beed","Purple Nutsedge":"Low","Bermuda Grass":"Low","Congress Grass":"Low","Pigweed":"Medium","Goosegrass":"Low","Common Purslane":"High"}
],
compInsights:{farmerSatLow:5,farmerSatMed:5,farmerSatHigh:5,weedEscape:4,ineffective:3,strongFit:3,convTotal:10}
}};
var SEG_IMAGES={paddy_ap:{opp:"ap_opportunity_map.png",comp:"ap_competition_map.png"},maize_mh:{opp:"mh_opportunity_map.png",comp:"mh_competition_map.png"}};
